CREATE SEQUENCE IF NOT EXISTS payment_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE payment
(
    id                    BIGINT       NOT NULL,
    reservation_id        BIGINT       NOT NULL,
    user_id               BIGINT       NOT NULL,
    amount                FLOAT        NOT NULL,
    currency              VARCHAR(255) NOT NULL,
    status                VARCHAR(255) NOT NULL,
    method                VARCHAR(255),
    paypal_transaction_id VARCHAR(255),
    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

CREATE TABLE paypal_outbox_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    aggregate_id   VARCHAR(255),
    aggregate_type VARCHAR(255),
    event_type     VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_paypal_outbox_events PRIMARY KEY (id)
);